[package]
name = "gal-bindings"
version = "0.1.0"
authors = ["Berrysoft <Strawberry_Str@hotmail.com>"]
edition = "2021"

[dependencies]
gal-primitive = { path = "../gal-primitive" }
gal-bindings-types = { path = "../gal-bindings-types" }
gal-bindings-impl = { path = "../gal-bindings-impl" }
serde = "1.0"
rmp-serde = "1.1"
log = "0.4"

[dev-dependencies]
serde_yaml = "0.8"
