[package]
name = "gal-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
gal-bindings-types = { path = "../gal-bindings-types" }
gal-fallback = { path = "../gal-fallback" }
gal-script = { path = "../gal-script" }
gal-locale = { path = "../gal-locale" }
num-traits = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
rmp-serde = "1.1"
anyhow = "1.0"
wasmtime = "0.38"
wasmtime-wasi = "0.38"
unicode-width = "0.1"
tokio = { version = "1", features = ["fs"] }
tokio-stream = { version = "0.1", features = ["fs"] }
async-stream = "0.3"

[dev-dependencies]
serde_yaml = "0.8"
lazy_static = "1.4"
tokio-test = "0.4"
