trigger:
  branches:
    include:
      - master

jobs:
- job: Build
  strategy:
    matrix:
      win-x64:
        platform: 'win'
        target: 'x86_64-pc-windows-msvc'
        image: 'windows-latest'
      linux-x64:
        platform: 'linux'
        target: 'x86_64-unknown-linux-gnu'
        image: 'ubuntu-22.04'
      macos-x64:
        platform: 'mac'
        target: 'x86_64-apple-darwin'
        image: 'macOS-latest'
      macos-arm64:
        platform: 'mac'
        target: 'aarch64-apple-darwin'
        image: 'macOS-latest'
  pool:
    vmImage: $(image)
  
  steps:
  - script: |
      sudo apt update
      sudo apt install libwebkit2gtk-4.0-dev libicu-dev
    condition: eq(variables.platform, 'linux')
    displayName: "Install dependencies on Linux"

  - pwsh: |
      rustup target add $(target)
      rustup target add wasm32-unknown-unknown
      rustup target add wasm32-wasi
    displayName: "Install targets"

  - pwsh: make plugins
    displayName: "Build plugins"

  - pwsh: make release-cross TARGET=$(target)
    displayName: "Build all"
