title: 団長の名場面
author: 冈田麿里
props:
  bg: 4
  bgs: bgs
  bgms: bgms
res:
  ja:
    ch_rd: ライド
    ch_org: オルガ
    ch_kdr: クーデリア
    ch_tkk: タカキ
    ch_td: チャド
    ch_ass: 暗殺者
    ch_mktk: 三日月
  zh_Hans:
    ch_rd: 莱德
    ch_org: 奥尔加
    ch_kdr: 古荻莉亚
    ch_tkk: 塔卡基
    ch_td: 查德
    ch_ass: 刺客
plugins:
  dir: ../plugins/
  modules:
    - basictex
    - media
base_lang: ja
paras:
  ja:
    -
      tag: pre_car
      title: 車の用意し
      texts:
        - |
          \ch{rd}団長！車の用意できました！\bg{0}
          \switch{おう！}{$end = false}
          \switch{止まるんじゃねぇぞ！}{$end = true}
          \switch{止まれ！}{}{false}
      next: \exec{if($end, "end", "walk")}
    -
      tag: walk
      title: 静かだ
      texts:
        - \ch{org}おう！じゃあな。
        - /kdr//はい、お気をつけて。
        - |
          /rd//なんか静かですね。街の中にはギャラルホルンもいないし本部とはえらい違いだ。\bg{1}
          \switch{安全}{}
          \switch{気を付け}{}{false}
        - /org//ああ。火星の戦力は軒並み向こうに回してんのかもな。
        - /rd//まっそんなのもう関係ないですけどね！
        - /org//上機嫌だな。
        - /rd/ガンバラナイト/そりゃそうですよ！みんな助かるし、\res{ch_tkk}も頑張ってたし、俺も\ruby{頑張らないと}{ガンバラナイト}！
        - /org//ああ。
        - そうだ。俺たちが今まで積み上げてきたもんは全部無駄じゃなかった。これからも俺たちが立ち止まらないかぎり道は続く。
      next: gun
    -
      tag: gun
      title: 何やってんだよ
      texts:
        - /td//ぐわっ！\bg{2}
        - /rd//団長？何やってんだよ？団長！
        - /org//ぐっ！うおぉ～～！
        - /ass//うおっ！あっ！
        - /org//はぁはぁはぁ……なんだよ、結構当たんじゃねぇか。ふっ……\bg{3}
        - /rd//だ……団長……あっ……あぁ……
        - /org//なんて声出してやがる……ライド。
        - /rd//だって……だって……\bgm{0}
        - /org//俺は鉄華団団長オルガ・イツカだぞ。こんくれぇなんてこたぁねぇ。
        - /rd//そんな……俺なんかのために……
        - /org//団員を守んのは俺の仕事だ。
        - /rd//でも！
        - /org//いいから行くぞ。皆が待ってんだ。それに……。
        - ミカ、やっと分かったんだ。
        - 俺たちにはたどりつく場所なんていらねぇ。ただ進み続けるだけでいい。止まんねぇかぎり、道は続く。
        - /mktk//謝ったら許さない。
        - /org//ああ分かってる。
      next: end
    -
      tag: end
      title: 止まるんじゃねぇぞ
      texts:
        - /org//俺は止まんねぇからよ、お前らが止まんねぇかぎり、その先に俺はいるぞ！\bgm{0}\bg{4}
        - /org//だからよ、止まるんじゃねぇぞ……
  zh_Hans:
    -
      tag: pre_car
      title: 备车
      texts:
        - |
          团长！车已经准备好了！
          \switch{哦！}
          \switch{不要停下来啊！}
          \switch{停下！}
    -
      tag: walk
      title: 安静
      texts:
        - 哦！那么我走了。
        - 好，路上小心。
        - |
          感觉真安静啊，街上也没有加拉尔霍恩的人，和总部差别真大啊。
          \switch{安全}
          \switch{小心}
        - 啊，可能是他们把火星的战力都调到那里去了。
        - 不过这也和我们没关系了。
        - 心情很愉快啊。
        - /rd/加把劲骑士/那是当然的了！大家也有救了，\res{ch_tkk}又那么努力，我也\ruby{要加油了}{是加把劲骑士}！
        - 啊。
        - 没错，我们至今为止所做的一切，并不是全部徒劳的。今后也是，只要我们不停下脚步，道路就会不断延伸。
    -
      tag: gun
      title: 你在干什么啊
      texts:
        - 咕哇！
        - 团长，你在干什么啊，团长！
        - 呃呃啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊！！！
        - 呜哦！啊！
        - 哈哈哈……什么嘛，我的枪法还挺准的嘛。呵……
        - 团……团长……啊……啊……
        - 你的声音为什么要颤抖，莱德。
        - 因为……因为……
        - 我可是铁华团团长奥尔加·伊兹卡啊，这点小伤无关紧要。
        - 为什么……要为了保护我……
        - 保护团员就是我的使命。
        - 但是！
        - 好了，快走吧！大家都在等着你们。而且……
        - 三日，我终于明白了。
        - 我们的目的地根本不重要，只要继续前进就好了，只要不停下脚步，道路就会不断延伸。
        - 道歉的话我是不会原谅你的。
        - 啊，我明白。
    -
      tag: end
      title: 不要停下来啊
      texts:
        - 我是不会停下来的，只要你们不停下来，那前面就一定有我！
        - 所以，不要停下来啊……
