[package]
name = "gal-locale"
version = "0.1.0"
edition = "2021"

[dependencies]
cfg-if = "1.0"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
anyhow = "1.0"

[target.'cfg(not(any(target_os = "windows", target_os = "macos")))'.dependencies]
rust_icu_sys = "2.0"
paste = "1.0"
