[package]
name = "gal-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
gal-bindings-types = { path = "../gal-bindings-types" }
gal-script = { path = "../gal-script" }
fallback = { path = "../fallback" }
locale = { path = "../locale" }
stream-future = "0.1"
async-trait = "0.1"
async-recursion = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1.0"
rmp-serde = "1.1"
anyhow = "1.0"
wasmer = "2.3"
wasmer-wasi = "2.3"
unicode-width = "0.1"
tokio = { version = "1", features = ["fs", "macros"] }
tokio-stream = { version = "0.1", features = ["fs"] }
pin-project = "1.0"
dirs = "4.0"

[dev-dependencies]
tokio = { version = "1", features = ["parking_lot", "rt"] }
