[package]
name = "gal-bindings-types"
version = "0.1.0"
authors = ["Berrysoft <Strawberry_Str@hotmail.com>"]
edition = "2021"

[dependencies]
gal-fallback = { path = "../gal-fallback" }
gal-script = { path = "../gal-script" }
serde = { version = "1.0", features = ["derive"] }
log = { version = "0.4", features = ["serde"] }
bitflags = "1.3"
